<?php
declare(strict_types=1);

namespace FacturaScripts\Plugins\WidgetEmail\Lib;

/**
 * Static blacklist of well-known disposable / throwaway email domains.
 *
 * Not exhaustive — intended for fast server-side detection of the most common
 * disposable providers. Update the list between CalVer releases as needed.
 */
class DisposableEmailDomains
{
    /** @var string[] */
    public const DOMAINS = [
        // --- guerrillamail family ---
        'guerrillamail.com',
        'guerrillamail.net',
        'guerrillamail.org',
        'guerrillamail.biz',
        'guerrillamail.de',
        'guerrillamail.info',
        'guerrillamailblock.com',
        'grr.la',
        'sharklasers.com',
        // --- 10minutemail family ---
        '10minutemail.com',
        '10minutemail.net',
        '10minutemail.org',
        '10minutemail.de',
        // --- mailinator family ---
        'mailinator.com',
        'mailinater.com',
        'suremail.info',
        'spamherelots.com',
        'putthisinyourspamdatabase.com',
        // --- trashmail family ---
        'trashmail.com',
        'trashmail.at',
        'trashmail.io',
        'trashmail.me',
        'trashmail.net',
        'trashmail.org',
        'trashmail.xyz',
        // --- yopmail family ---
        'yopmail.com',
        'yopmail.fr',
        'cool.fr.nf',
        'jetable.fr.nf',
        'nospam.ze.tc',
        // --- tempmail family ---
        'tempmail.com',
        'tempmail.net',
        'tempmail.org',
        'temp-mail.org',
        'temp-mail.io',
        'tempr.email',
        'tempail.com',
        'tempemail.net',
        // --- throwaway ---
        'throwaway.email',
        'throwam.com',
        // --- misc popular disposables ---
        'maildrop.cc',
        'discard.email',
        'dispostable.com',
        'fakeinbox.com',
        'mailnull.com',
        'spam4.me',
        'spam.la',
        'spamavert.com',
        'spamgourmet.com',
        'spamgourmet.net',
        'spamgourmet.org',
        'spamhereplease.com',
        'mailexpire.com',
        'safetymail.info',
        'e4ward.com',
        'binkmail.com',
        'bobmail.info',
        'chammy.info',
        'devnullmail.com',
        'filzmail.com',
        'get2mail.fr',
        'gishpuppy.com',
        'hailmail.net',
        'ihateyoualot.info',
        'imails.info',
        'jnxjn.com',
        'klzlk.com',
        'lookugly.com',
        'lortemail.dk',
        'mailtome.de',
        'mailscrap.com',
        'mt2014.com',
        'mt2015.com',
        'nwldx.com',
        'objectmail.com',
        'obobbo.com',
        'oneoffmail.com',
        'pepbot.com',
        'pfui.ru',
        'qq.my',
        'rklips.com',
        'rmqkr.net',
        'royal.net',
        'rppkn.com',
        's0ny.net',
        'sandelf.de',
        'shieldedmail.com',
        'snakemail.com',
        'sogetthis.com',
        'soodonims.com',
        'supergreatmail.com',
        'suremail.info',
        'sweetxxx.de',
        'tafmail.com',
        'tagyourself.com',
        'teewars.org',
        'tknzz.email',
        'tlpn.org',
        'tmpjoe.com',
        'trbvm.com',
        'turual.com',
        'uggsrock.com',
        'uroid.com',
        'vomoto.com',
        'wuzupmail.net',
        'xemaps.com',
        'xents.com',
        'xmaily.com',
        'xoxy.net',
        'yep.it',
        'yogamaven.com',
        'yuurok.com',
        'z1p.biz',
        'zippymail.info',
        'zoemail.com',
        'zomg.info',
    ];
}
